name: Update target data
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Update target data'
        required: false

jobs:
  update_target_data:
    if: github.repository_owner == 'ai4castinghub'
    runs-on: macOS-latest
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        run: |
          install.packages(c("dplyr", "lubridate", "readxl","tidyr"))
        shell: Rscript {0}
        
      - name: Generate target csv files
        run:  Rscript scripts/get_target_data.R
        
      - name: Add new files
        run: git add target-data/ 
          
      - name: Commit changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'update rvdss data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
